-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Network"
(
    id text NOT NULL,
    name text,
    website text,
    "publisher-id" text,
    "publicationDate" date,
    "collectionDate" date,
    "crs-name" text NOT NULL,
    "crs-uri" text NOT NULL,
    accuracy integer,
    "accuracy-details" text,
    language text,
    PRIMARY KEY (id)
);

COMMENT ON TABLE public."Network"
    IS 'Network definition based on the Open Fiber Data Standar
https://open-fibre-data-standard.readthedocs.io/en/latest/reference/schema.html#structure';

CREATE TABLE IF NOT EXISTS public."Node"
(
    id_networks text NOT NULL,
    id text NOT NULL,
    name text,
    "phase-id" text NOT NULL,
    "phase-name" text,
    status text,
    location point,
    "streetAddress" text,
    locality text,
    region text,
    "postalCode" text,
    country text,
    type text,
    "accessPoint" text,
    power boolean,
    technologies text,
    "physicalInfrastructureProvider" text,
    PRIMARY KEY (id)
);

COMMENT ON TABLE public."Node"
    IS 'Nodes 
https://open-fibre-data-standard.readthedocs.io/en/latest/reference/schema.html#node';

CREATE TABLE IF NOT EXISTS public."Span"
(
    id_network text NOT NULL,
    id text NOT NULL,
    name text,
    "phase-id" text NOT NULL,
    "phase-name" text,
    status text,
    "readyForServiceDate" date,
    start text,
    "end" text,
    directed boolean,
    route line,
    "transmissionMedium" text,
    deployment text,
    "deploymentDetails-description" text,
    "darkFibre" boolean,
    "fibreType" text,
    "fibreSubtype" text,
    "fibreSubtype-description" text,
    "fibreCount" integer,
    "fibreLength" integer,
    technologies text,
    capacity integer,
    "capacityDetails-description" text,
    countries text,
    PRIMARY KEY (id)
);

COMMENT ON TABLE public."Span"
    IS 'Span
https://open-fibre-data-standard.readthedocs.io/en/latest/reference/publication_formats/csv.html#spans';

CREATE TABLE IF NOT EXISTS public."SpanNetworkProvider"
(
    id_network text NOT NULL,
    id text NOT NULL,
    id_organization text NOT NULL,
    name text,
    PRIMARY KEY (id)
);

COMMENT ON TABLE public."SpanNetworkProvider"
    IS 'https://open-fibre-data-standard.readthedocs.io/en/latest/reference/publication_formats/csv.html#spans_networkProviders';

CREATE TABLE IF NOT EXISTS public."Phase"
(
    id_network text NOT NULL,
    id text NOT NULL,
    name text,
    description text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."PhaseFunder"
(
    id_network text NOT NULL,
    id_phase text NOT NULL,
    id_funder text NOT NULL,
    description text
);

COMMENT ON TABLE public."PhaseFunder"
    IS 'https://open-fibre-data-standard.readthedocs.io/en/latest/reference/publication_formats/csv.html#phases_funders';

CREATE TABLE IF NOT EXISTS public."Organisation"
(
    id_network text NOT NULL,
    id text NOT NULL,
    name text,
    "identifier-id" text,
    "identifier-scheme" text,
    "identifier-legalName" text,
    "identifier-uri" text,
    country text,
    roles text,
    "roleDetails" text,
    website text,
    logo text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Contract"
(
    id_network text NOT NULL,
    id text NOT NULL,
    title text,
    description text,
    type text,
    "value-amount" integer,
    "value-currency" text,
    "dateSigned" text,
    PRIMARY KEY (id)
);

COMMENT ON TABLE public."Contract"
    IS 'https://open-fibre-data-standard.readthedocs.io/en/latest/reference/publication_formats/csv.html#Contracts';

CREATE TABLE IF NOT EXISTS public."NodeInternationalConnection"
(
    id_network text NOT NULL,
    id_node text NOT NULL,
    id text NOT NULL,
    "streetAddress" text,
    locality text,
    region text,
    "postalCode" text,
    country text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."NodeNetworkProvider"
(
    id_network text NOT NULL,
    id_node text NOT NULL,
    id text NOT NULL,
    name text,
    PRIMARY KEY (id)
);

COMMENT ON TABLE public."NodeNetworkProvider"
    IS 'https://open-fibre-data-standard.readthedocs.io/en/latest/reference/publication_formats/csv.html#nodes-networkproviders';

CREATE TABLE IF NOT EXISTS public."ContractDocument"
(
    id_network text NOT NULL,
    id text NOT NULL,
    title text,
    description text,
    url text,
    format text,
    id_contract text NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE public."ContractDocument"
    IS 'https://open-fibre-data-standard.readthedocs.io/en/latest/reference/publication_formats/csv.html#contracts-documents';

CREATE TABLE IF NOT EXISTS public."ContractPhases"
(
    id_network text NOT NULL,
    id_contract text NOT NULL,
    id_phase text NOT NULL,
    name text,
    PRIMARY KEY (id_phase, id_contract)
);

COMMENT ON TABLE public."ContractPhases"
    IS 'https://open-fibre-data-standard.readthedocs.io/en/latest/reference/publication_formats/csv.html#contracts-relatedphases';

ALTER TABLE IF EXISTS public."Node"
    ADD CONSTRAINT network FOREIGN KEY (id_networks)
    REFERENCES public."Network" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Span"
    ADD CONSTRAINT network FOREIGN KEY (id_network)
    REFERENCES public."Network" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."SpanNetworkProvider"
    ADD CONSTRAINT spans FOREIGN KEY (id)
    REFERENCES public."Span" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Phase"
    ADD CONSTRAINT network FOREIGN KEY (id_network)
    REFERENCES public."Network" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PhaseFunder"
    ADD CONSTRAINT phase FOREIGN KEY (id_phase)
    REFERENCES public."Phase" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PhaseFunder"
    ADD CONSTRAINT funder FOREIGN KEY (id_funder)
    REFERENCES public."Organisation" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Organisation"
    ADD CONSTRAINT network FOREIGN KEY (id_network)
    REFERENCES public."Network" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Contract"
    ADD CONSTRAINT network FOREIGN KEY (id_network)
    REFERENCES public."Network" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."NodeInternationalConnection"
    ADD CONSTRAINT node FOREIGN KEY (id_node)
    REFERENCES public."Node" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."NodeNetworkProvider"
    ADD CONSTRAINT node FOREIGN KEY (id_node)
    REFERENCES public."Node" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."ContractDocument"
    ADD CONSTRAINT network FOREIGN KEY (id_network)
    REFERENCES public."Network" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."ContractDocument"
    ADD CONSTRAINT contract FOREIGN KEY (id_contract)
    REFERENCES public."Contract" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."ContractPhases"
    ADD CONSTRAINT contract FOREIGN KEY (id_contract, id_phase)
    REFERENCES public."Contract" (id, id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."ContractPhases"
    ADD CONSTRAINT phase FOREIGN KEY (id_phase)
    REFERENCES public."Phase" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;